/*
 * PanelApp API
 *
 * PanelApp API
 *
 * OpenAPI spec version: v1
 * Contact: panelapp@genomicsengland.co.uk
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct HistoricalSnapshot {
    #[serde(rename = "data")]
    data: Value,
    #[serde(rename = "signed_off_date")]
    signed_off_date: Option<String>,
}

impl HistoricalSnapshot {
    pub fn new(data: Value) -> HistoricalSnapshot {
        HistoricalSnapshot {
            data,
            signed_off_date: None,
        }
    }

    pub fn set_data(&mut self, data: Value) {
        self.data = data;
    }

    pub fn with_data(mut self, data: Value) -> HistoricalSnapshot {
        self.data = data;
        self
    }

    pub fn data(&self) -> &Value {
        &self.data
    }

    pub fn set_signed_off_date(&mut self, signed_off_date: String) {
        self.signed_off_date = Some(signed_off_date);
    }

    pub fn with_signed_off_date(mut self, signed_off_date: String) -> HistoricalSnapshot {
        self.signed_off_date = Some(signed_off_date);
        self
    }

    pub fn signed_off_date(&self) -> Option<&String> {
        self.signed_off_date.as_ref()
    }

    pub fn reset_signed_off_date(&mut self) {
        self.signed_off_date = None;
    }
}
